### ISSUE TITLE
verbose and notice fail for Logger subclasses

### ISSUE THREAD

**Issue by stefraynaud** [VACUMM/vacumm#2]
It creates an infinite loop, probably because the log method calls itself due to a non robust use of super().
Here is an example:

``` python
from vacumm.misc.log import Logger
class Logger2(Logger): pass

Logger2('test').verbose('msg')
```

**Comment by jowilk** [comment]
Should be fixed in master 77ab4d142199452960056b1ee85013df05e3a984
